# Generated by Django 5.2.11 on 2026-03-26 14:50

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='end_date',
            field=models.DateField(verbose_name='Дата завершення'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.room', verbose_name='Кімната'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='start_date',
            field=models.DateField(verbose_name='Дата початку'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Користувач'),
        ),
        migrations.AlterField(
            model_name='room',
            name='capacity',
            field=models.IntegerField(verbose_name='Вмістимість (осіб)'),
        ),
        migrations.AlterField(
            model_name='room',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Назва кімнати'),
        ),
        migrations.AlterField(
            model_name='room',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Ціна за добу'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('conf', 'Конференц-зал'), ('office', 'Офіс'), ('meet', 'Кімната для зустрічей')], max_length=10, verbose_name='Тип'),
        ),
    ]
